### ISSUE TITLE
solo feature got problem

### ISSUE THREAD

**Issue by bangdrie** [Afiniel-tech/Yiimpool-Installer#5]
There is a miner in my pool with 10 workers. 4 of them are mining solo. If ANY of his rigs find a block, he gets paid the whole block reward just like all his workers are in solo. Also, if any other miner hits a block, he gets a share according to his hashrates!

**Comment by Nim1com** [comment]
What is the problem?

**Comment by afiniel** [comment]
Solo is fixed, find it here: Afiniel-tech/yiimp/pull/5
