### ISSUE TITLE
Got a mysql problem with a Installation step!

### ISSUE THREAD

**Issue by Nim1com** [Afiniel-tech/Yiimpool-Installer#6]
Creating DB users for YiiMP...
sudo: mysql: command not found
An error occurred in line 39 of file db.sh:
sudo mysql -u root -p"${DBRootPassword}" -e "$SQL"

**Comment by afiniel** [comment]
I will try install and see if i have the same issue.

be back soon

**Comment by afiniel** [comment]
I don't get any error, are you sure you followed the install instructions?
- > Reopen if you still have problem
![bild](https://user-images.githubusercontent.com/44875524/182378733-349f3bff-45d2-4467-8506-58223f9b75c2.png)
